encoding: utf-8
author: DoSun
title: DoSun's Blog
date_format: '%Y-%m-%d'
icon: "/assets/images/icon.ico"
description: 没事写写东西,记点笔记

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: posts
      type: post
 
sidebar_home_link: true

google_analytics: UA-106863689-1
uyan_id: 2145318

github:
  profile: https://github.com/XDfield

email: chenxuan958864951@qq.com
steam: http://steamcommunity.com/id/XDfield/

img:
  link: http://ows0v592v.bkt.clouddn.com/